import { ADMIN_SCOPE } from "../engine/risk.js";
import type { Inventory } from "../schemas/inventory.js";

export interface RuntimeOptions {
  /** Blast radius at or above which a single invocation is flagged. */
  highBlast?: number;
  /** Writing-call count in the window that counts as a destructive burst. */
  burstCount?: number;
  burstWindow?: string;
  /** Window for the three-admin-call privilege-escalation sequence. */
  escalationWindow?: string;
  /** Window for the credential-read-then-exfiltrate sequence. */
  exfilWindow?: string;
  /** Event source: "nats" emits a NATS connector + ingest stream. Default: none. */
  source?: "none" | "nats";
  /** NATS server URL when source is "nats". */
  natsUrl?: string;
  /** NATS subject the events arrive on when source is "nats". */
  subject?: string;
}

/** The OAuth scopes admin-scoped tools legitimately use, as `oauth:<scope>`. */
function allowedAdminScopes(inventory: Inventory): string[] {
  const scopes = new Set<string>();
  for (const server of inventory.servers) {
    for (const tool of server.tools) {
      if (!tool.effects.scope.some((s) => ADMIN_SCOPE.test(s))) continue;
      for (const s of tool.effects.scope) scopes.add(`oauth:${s}`);
    }
  }
  return [...scopes].sort();
}

/**
 * Generate the Varpulis VPL ruleset for runtime MCP governance, parameterised
 * from the static inventory. The rules are the runtime twins of the static
 * findings: a high-blast tool firing, a caller outside an admin tool's scopes,
 * a privilege-escalation sequence, a credential-then-exfiltrate sequence, and a
 * destructive burst. Syntax is grounded in the varpulis/varpulis .vpl examples.
 */
export function generateVpl(inventory: Inventory, opts: RuntimeOptions = {}): string {
  const highBlast = opts.highBlast ?? 6;
  const burstCount = opts.burstCount ?? 5;
  const burstWindow = opts.burstWindow ?? "1m";
  const escWindow = opts.escalationWindow ?? "2m";
  const exfilWindow = opts.exfilWindow ?? "1m";
  const scopes = allowedAdminScopes(inventory);
  const scopeList = (scopes.length > 0 ? scopes : ["oauth:admin"]).map((s) => `"${s}"`).join(", ");
  const useNats = opts.source === "nats";
  const natsUrl = opts.natsUrl ?? "nats://localhost:4222";
  const subject = opts.subject ?? "mcp.toolcalls";
  const connectorDecl = useNats ? `connector McpBus = nats(url: "${natsUrl}")\n\n` : "";
  const ingestStream = useNats
    ? `\n# Ingest the gateway-captured tool calls from the NATS broker.\nstream McpIngest = McpToolCall.from(McpBus, topic: "${subject}")\n`
    : "";
  const feedHint = useNats
    ? `agentic-compliance-scan --bridge <inventory.json> --sink nats --subject ${subject}`
    : "agentic-compliance-scan --bridge <inventory.json> --sink console";

  return `# MCP runtime governance — generated by agentic-compliance-scan.
# Each McpToolCall is a gateway-captured tools/call, enriched with the risk
# profile the static scan computed for that tool (effects + blast radius). Feed
# events with: ${feedHint}.

${connectorDecl}event McpToolCall:
    agent: str
    server: str
    tool: str
    caller_scope: str
    writes: bool
    side_effects: bool
    external_access: bool
    admin: bool
    credentials: bool
    personal_data: bool
    blast_radius: int
${ingestStream}
# 1. A require-approval tool actually fired (the runtime twin of the --policy
#    "require approval" recommendation): blast radius at or above ${highBlast}.
stream HighBlastInvocation = McpToolCall
    .where(blast_radius >= ${highBlast})
    .emit(event_type: "mcp.high_blast_invocation", agent: agent, server: server, tool: tool, blast_radius: blast_radius)

# 2. An admin-scoped tool fired by a caller outside its allowed OAuth scopes.
stream CallerScopeViolation = McpToolCall
    .where(admin and caller_scope not in [${scopeList}])
    .emit(event_type: "mcp.caller_scope_violation", agent: agent, tool: tool, caller_scope: caller_scope)

# 3. Privilege escalation: three admin calls by the same agent within ${escWindow}.
stream PrivilegeEscalation = McpToolCall as a
    -> McpToolCall where admin and agent == a.agent as b
    -> McpToolCall where admin and agent == a.agent as c
    .within(${escWindow})
    .where(a.admin == true)
    .emit(event_type: "mcp.privilege_escalation", agent: a.agent, t1: a.tool, t2: b.tool, t3: c.tool)

# 4. Credential read then external send by the same agent within ${exfilWindow}.
stream CredentialExfil = McpToolCall as a
    -> McpToolCall where external_access and agent == a.agent as b
    .within(${exfilWindow})
    .where(a.credentials == true)
    .emit(event_type: "mcp.credential_exfil", agent: a.agent, cred_tool: a.tool, exfil_tool: b.tool)

# 5. Destructive burst: ${burstCount} or more writing calls by one agent in ${burstWindow}.
stream DestructiveBurst = McpToolCall
    .where(writes == true)
    .window(${burstWindow})
    .aggregate(agent: last(agent), n: count())
    .where(n >= ${burstCount})
    .emit(event_type: "mcp.destructive_burst", agent: agent, count: n)
`;
}
